/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Aji
 */
public class Form_DataKoran extends javax.swing.JDialog {
  DefaultTableModel model = new DefaultTableModel();
  int jml_eks =0 , wajibBayar=0;
      String wajibBayarrr;
    /**
     * Creates new form Form_DataKoran
     */
    public Form_DataKoran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kelas.koneksi.koneksi();
        headerTable();
        tampilPengguna();
        tombol(false);
        setLocationRelativeTo(null);
        total();
        ket_Total();
    }
    private String str;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtx_no = new javax.swing.JTextField();
        jtx_nama = new javax.swing.JTextField();
        jtx_kota = new javax.swing.JTextField();
        jtx_hp = new javax.swing.JTextField();
        jtx_jmleks = new javax.swing.JTextField();
        jtx_wajibbayar = new javax.swing.JTextField();
        jtx_biayakirim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtx_iklan = new javax.swing.JTextField();
        jtx_telahbayar = new javax.swing.JTextField();
        jtx_keterangan = new javax.swing.JTextField();
        jbt_baru = new javax.swing.JButton();
        jbt_simpan = new javax.swing.JButton();
        jbt_ubah = new javax.swing.JButton();
        jbt_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Data Koran");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/Medinas.jpg")).getImage());
        setPreferredSize(new java.awt.Dimension(910, 670));

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("Form Data Koran");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("No");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Kab/Kota");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("No. HP");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah Eks");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Wajib Bayar");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Biaya Kirim");

        jtx_no.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtx_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_noActionPerformed(evt);
            }
        });

        jtx_nama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtx_kota.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtx_hp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtx_jmleks.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtx_jmleks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtx_jmleksKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtx_jmleksKeyTyped(evt);
            }
        });

        jtx_wajibbayar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtx_wajibbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtx_wajibbayarKeyTyped(evt);
            }
        });

        jtx_biayakirim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtx_biayakirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtx_biayakirimKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Iklan");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Telah Bayar");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Keterangan");

        jtx_iklan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtx_iklan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtx_iklanKeyTyped(evt);
            }
        });

        jtx_telahbayar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtx_telahbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtx_telahbayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtx_telahbayarKeyTyped(evt);
            }
        });

        jtx_keterangan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jbt_baru.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jbt_baru.setText("Baru");
        jbt_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_baruActionPerformed(evt);
            }
        });

        jbt_simpan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jbt_simpan.setText("Simpan");
        jbt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_simpanActionPerformed(evt);
            }
        });

        jbt_ubah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jbt_ubah.setText("Ubah");
        jbt_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_ubahActionPerformed(evt);
            }
        });

        jbt_hapus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jbt_hapus.setText("Hapus");
        jbt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_hapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Cari :");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField1.setText("Cari Nama");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(24, 24, 24)
                                        .addComponent(jtx_jmleks, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtx_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtx_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtx_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtx_no, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbt_baru))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(542, 542, 542)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbt_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbt_ubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_hapus))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtx_keterangan)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtx_telahbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtx_iklan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtx_biayakirim, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtx_wajibbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtx_wajibbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtx_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtx_biayakirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtx_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtx_kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtx_iklan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtx_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtx_telahbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtx_jmleks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtx_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_baru)
                    .addComponent(jbt_simpan)
                    .addComponent(jbt_ubah)
                    .addComponent(jbt_hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu4.setText("Beranda");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu1.setText("Data");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Tambah Admin");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Tambah Data Koran");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Keluar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laporan");

        jMenuItem5.setText("Laporan");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Bantuan");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_baruActionPerformed
        // TODO add your handling code here:
        tombol(true);
    }//GEN-LAST:event_jbt_baruActionPerformed

    private void jbt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_simpanActionPerformed
        // TODO add your handling code here:
              try {
            kelas.koneksi.st.executeUpdate(
           "insert into tbl_koran values ('"+jtx_no.getText()+"','"+jtx_nama.getText()+"','"+jtx_kota.getText()+"','"+jtx_hp.getText()+"','"+jtx_jmleks.getText()+"','"+jtx_wajibbayar.getText()+"','"+jtx_biayakirim.getText()+"','"+jtx_iklan.getText()+"','"+jtx_telahbayar.getText()+"','"+jtx_keterangan.getText()+"' )");
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
            tampilPengguna();
            tombol(false);
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror Simpan : "+e);
            }
  
    }//GEN-LAST:event_jbt_simpanActionPerformed

    private void jbt_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_ubahActionPerformed
        // TODO add your handling code here:
        try {
        kelas.koneksi.st.executeUpdate("update tbl_koran set nama = '"+jtx_nama.getText()+"',kota='"+jtx_kota.getText()+"',no_hp='"+jtx_hp.getText()+"',jml_eks='"+jtx_jmleks.getText()+"',wajib_bayar='"+jtx_wajibbayar.getText()+"',biaya_kirim='"+jtx_biayakirim.getText()+"',iklan='"+jtx_iklan.getText()+"',telah_bayar='"+jtx_telahbayar.getText()+"',keterangan='"+jtx_keterangan.getText()+"' where no='"+jtx_no.getText()+"' ");
         JOptionPane.showMessageDialog(null,"Berhasil Merubah ");
         tampilPengguna();
         tombol(false);
         } catch (Exception e) {
         JOptionPane.showMessageDialog(null,"Eror Ubah : "+ e);
         }
    }//GEN-LAST:event_jbt_ubahActionPerformed

    private void jbt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_hapusActionPerformed
        // TODO add your handling code here:
        try {
        kelas.koneksi.st.executeUpdate("delete from tbl_koran where no = '"+jtx_no.getText()+"' ");
        JOptionPane.showMessageDialog(null,"Berhasil Menghapus ");
        tampilPengguna();
        tombol(false);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null,"Eror Hapus : "+ e);
        }
    }//GEN-LAST:event_jbt_hapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedColumnCount()==1){
        int row = jTable1.getSelectedRow();
        jtx_no.setText(jTable1.getValueAt(row, 0).toString());
        jtx_nama.setText(jTable1.getValueAt(row, 1).toString());
        jtx_kota.setText(jTable1.getValueAt(row, 2).toString());
        jtx_hp.setText(jTable1.getValueAt(row, 3).toString());
        jtx_jmleks.setText(jTable1.getValueAt(row, 4).toString());
        jtx_wajibbayar.setText(jTable1.getValueAt(row, 5).toString());
        jtx_biayakirim.setText(jTable1.getValueAt(row, 6).toString());
        jtx_iklan.setText(jTable1.getValueAt(row, 7).toString());
        jtx_telahbayar.setText(jTable1.getValueAt(row, 8).toString());
        jtx_keterangan.setText(jTable1.getValueAt(row, 9).toString());
        
        tombol(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        CariPengguna();
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jtx_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_noActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        new Form_Menu_Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Form_Admin x = new Form_Admin(null, rootPaneCheckingEnabled);
        x.setVisible(true);
        //        new Menu_Utama().setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
       // Form_DataKoran x = new Form_DataKoran(null, rootPaneCheckingEnabled);
       // x.setVisible(true);
        new Form_DataKoran(null, true).setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Form_Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
       new Form_Laporan().setVisible(true);
       dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        new Bantuan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jtx_jmleksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_jmleksKeyReleased
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_jtx_jmleksKeyReleased

    private void jtx_jmleksKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_jmleksKeyTyped
        // TODO add your handling code here:
char karakter = evt.getKeyChar();
if (!(((karakter>= '0' )&&(karakter <='9')||(karakter==KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE)))){
getToolkit().beep();
evt.consume();
        }

    }//GEN-LAST:event_jtx_jmleksKeyTyped

    private void jtx_wajibbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_wajibbayarKeyTyped
char karakter = evt.getKeyChar();
if (!(((karakter>= '0' )&&(karakter <='9')||(karakter==KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE)))){
getToolkit().beep();
evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_wajibbayarKeyTyped

    private void jtx_biayakirimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_biayakirimKeyTyped
char karakter = evt.getKeyChar();
if (!(((karakter>= '0' )&&(karakter <='9')||(karakter==KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE)))){
getToolkit().beep();
evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_biayakirimKeyTyped

    private void jtx_iklanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_iklanKeyTyped
char karakter = evt.getKeyChar();
if (!(((karakter>= '0' )&&(karakter <='9')||(karakter==KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE)))){
getToolkit().beep();
evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_iklanKeyTyped

    private void jtx_telahbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_telahbayarKeyTyped
char karakter = evt.getKeyChar();
if (!(((karakter>= '0' )&&(karakter <='9')||(karakter==KeyEvent.VK_BACK_SPACE)||(karakter==KeyEvent.VK_DELETE)))){
getToolkit().beep();
evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_telahbayarKeyTyped

    private void jtx_telahbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtx_telahbayarKeyReleased
ket_Total();
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_telahbayarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_DataKoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_DataKoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_DataKoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_DataKoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_DataKoran dialog = new Form_DataKoran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbt_baru;
    private javax.swing.JButton jbt_hapus;
    private javax.swing.JButton jbt_simpan;
    private javax.swing.JButton jbt_ubah;
    private javax.swing.JTextField jtx_biayakirim;
    private javax.swing.JTextField jtx_hp;
    private javax.swing.JTextField jtx_iklan;
    private javax.swing.JTextField jtx_jmleks;
    private javax.swing.JTextField jtx_keterangan;
    private javax.swing.JTextField jtx_kota;
    private javax.swing.JTextField jtx_nama;
    private javax.swing.JTextField jtx_no;
    private javax.swing.JTextField jtx_telahbayar;
    private javax.swing.JTextField jtx_wajibbayar;
    // End of variables declaration//GEN-END:variables


      void bersih(){
         jtx_no.setText("");
         jtx_nama.setText("");
         jtx_kota.setText("");
         jtx_hp.setText("");
         jtx_jmleks.setText("");
         jtx_wajibbayar.setText("");
         jtx_biayakirim.setText("");
         jtx_iklan.setText("");
         jtx_telahbayar.setText("");
         jtx_keterangan.setText("");
         jTextField1.setText("Cari Nama");
         }//ini blok bersih
        
        void tombol(boolean status){
         jbt_baru.setEnabled(true);
         jbt_simpan.setEnabled(status);
         jbt_ubah.setEnabled(status);
         jbt_hapus.setEnabled(status);
         jTextField1.setText("Cari Nama");
         }
        
    private void headerTable(){
         model = new DefaultTableModel();
         model.addColumn("No");
         model.addColumn("Nama");
         model.addColumn("Kota/Kab");
         model.addColumn("No. HP");
         model.addColumn("Jumlah Eks");
         model.addColumn("Wajib Bayar");
         model.addColumn("Biaya Kirim");
         model.addColumn("Iklan");
         model.addColumn("Telah Bayar");
         model.addColumn("Keterangan");
         
         jTable1.setModel(model);
         }

    public void tampilPengguna(){
         model.getDataVector().removeAllElements();
         try {
         ResultSet rs=kelas.koneksi.st.executeQuery("select * from tbl_koran");
         while(rs.next()){
         Object[] data = new Object[10];
         data[0]=(rs.getString(1));
         data[1]=(rs.getString(2));
         data[2]=(rs.getString(3));
         data[3]=(rs.getString(4));
         data[4]=(rs.getString(5));
         data[5]=(rs.getString(6));
         data[6]=(rs.getString(7));
         data[7]=(rs.getString(8));
         data[8]=(rs.getString(9));
         data[9]=(rs.getString(10));
         model.addRow(data);
         }//ini blok while
         } catch (Exception e) {
         JOptionPane.showMessageDialog(null,"eror tampil : "+ e);
         } //ini blok catch
         bersih();
         }
    
    public void CariPengguna (){
 model.getDataVector().removeAllElements();
 try {
 ResultSet rs=kelas.koneksi.st.executeQuery("select * from tbl_koran where nama like '%"+jTextField1.getText()+"%' ");
 while(rs.next()){
         Object[] data = new Object[10];
         data[0]=(rs.getString(1));
         data[1]=(rs.getString(2));
         data[2]=(rs.getString(3));
         data[3]=(rs.getString(4));
         data[4]=(rs.getString(5));
         data[5]=(rs.getString(6));
         data[6]=(rs.getString(7));
         data[7]=(rs.getString(8));
         data[8]=(rs.getString(9));
         data[9]=(rs.getString(10));
         model.addRow(data);
 }//ini blok while
 } catch (Exception e) {
 JOptionPane.showMessageDialog(null,"eror tampil : "+ e);
 } //ini blok catch
 }
    
    public void total (){
    try {
        jml_eks = Integer.parseInt(jtx_jmleks.getText());
       //bayar1=Integer.parseInt(txbanyak.getText());
       wajibBayar = jml_eks * 5000;
       DecimalFormat f = new DecimalFormat("#.#");
       wajibBayarrr = String.valueOf(f.format(wajibBayar));
       jtx_wajibbayar.setText(wajibBayarrr);
    }
     catch (Exception e){

        }
    }
    public void ket_Total(){
      int telahBayar =0, iklan =0, biayaKirim = 0, ket =0;
      String kettt;  
        try {
       biayaKirim = Integer.parseInt(jtx_biayakirim.getText());
       iklan = Integer.parseInt(jtx_iklan.getText());
       telahBayar = Integer.parseInt(jtx_telahbayar.getText());
       
       ket = (wajibBayar + iklan + biayaKirim)-telahBayar;
       DecimalFormat f = new DecimalFormat("#.#");
       kettt = String.valueOf(f.format(ket));
       jtx_keterangan.setText(kettt);
    }
     catch (Exception e){

        }
    }
}
